name: Release

on:
  push:
    tags:
      - 'v*'   # e.g., v0.1.0

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build zip
        run: |
          zip -r AIMineSwitch-${{ github.ref_name }}.zip . -x '*/.git/*' '*/.github/*' '*/venv/*' '*/.venv/*' '*.pyc' '__pycache__/*'
          ls -lah AIMineSwitch-${{ github.ref_name }}.zip

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: AIMineSwitch-${{ github.ref_name }}.zip
          generate_release_notes: true
